name: First Bash

on:
  push:
    branches: 
      - "*"

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
     env: 
      MY_SECRET: ${{ secrets.MY_SECRET}}
    - run: |
        npm install
     

